App.platform = "Android";
App.rootUrl = "https://worldsurveykit.com";
App.fbid = "271724712973440";
App.bgImage = "images/sky.jpg";
App.logo = "images/wsk.png";
App.organizationsName = "World Survey Kit";
App.emailToName = "worldsurveykit";
App.emailProvider = "outlook.com";
App.helpPage = "https://bitbucket.org/ntheile/wsk/issues";