// <auto-generated />
namespace WorldSurveyKit.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    public sealed partial class ResponseVarcharMAX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResponseVarcharMAX));

        string IMigrationMetadata.Id
        {
            get { return "201306021808580_ResponseVarcharMAX"; }
        }

        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
